package com.entuition.wekend.model.data.user;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.entuition.wekend.model.Constants;

import java.util.Set;

/**
 * Created by ryukgoo on 2015. 12. 16..
 */
@DynamoDBTable(tableName = Constants.USER_TABLE)
public class UserInfo {

    private static final String INDEX_USERNAME = Constants.INDEX_USERNAME;
    private static final String INDEX_NICKNAME = Constants.INDEX_NICKNAME;

    private static final String ATTRIBUTE_USERNAME = Constants.ATTRIBUTE_USERNAME;
    private static final String ATTRIBUTE_HASHED_PASSWORD = Constants.ATTRIBUTE_HASHED_PASSWORD;
    private static final String ATTRIBUTE_STATUS = Constants.ATTRIBUTE_STATUS;
    private static final String ATTRIBUTE_USERID = Constants.ATTRIBUTE_USERID;
    private static final String ATTRIBUTE_REGISTERED_TIME = Constants.ATTRIBUTE_REGISTERED_TIME;
    private static final String ATTRIBUTE_NICKNAME = Constants.ATTRIBUTE_NICKNAME;
    private static final String ATTRIBUTE_GENDER = Constants.ATTRIBUTE_GENDER;
    private static final String ATTRIBUTE_BIRTH = Constants.ATTRIBUTE_BIRTH;
    private static final String ATTRIBUTE_PHONE = Constants.ATTRIBUTE_PHONE;
    private static final String ATTRIBUTE_PHOTOS = Constants.ATTRIBUTE_PHOTOS;
    private static final String ATTRIBUTE_BALLOON = Constants.ATTRIBUTE_BALLOON;
    private static final String ATTRIBUTE_ENDPOINT_ARN = Constants.ATTRIBUTE_ENDPOINT_ARN;
    private static final String ATTRIBUTE_NEW_LIKE_COUNT = Constants.ATTRIBUTE_NEW_LIKE_COUNT;
    private static final String ATTRIBUTE_NEW_SEND_COUNT = Constants.ATTRIBUTE_NEW_SEND_COUNT;
    private static final String ATTRIBUTE_NEW_RECEIVE_COUNT = Constants.ATTRIBUTE_NEW_RECEIVE_COUNT;

    private String userId;
    private String username;
    private String hashedPassword;
    private String status;
    private String registeredTime;

    private String nickname;
    private String gender;
    private int birth;
    private String phone;
    private Set<String> photos;
    private int balloon;
    private String endpointARN;
    private int newLikeCount;
    private int newSendCount;
    private int newReceiveCount;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = ATTRIBUTE_USERID)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userid) {
        this.userId = userid;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = INDEX_USERNAME)
    @DynamoDBAttribute(attributeName = ATTRIBUTE_USERNAME)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_HASHED_PASSWORD)
    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_STATUS)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_REGISTERED_TIME)
    public String getRegisteredTime() {
        return registeredTime;
    }

    public void setRegisteredTime(String registeredTime) {
        this.registeredTime = registeredTime;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = INDEX_NICKNAME)
    @DynamoDBAttribute(attributeName = ATTRIBUTE_NICKNAME)
    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_GENDER)
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_BIRTH)
    public int getBirth() {
        return birth;
    }

    public void setBirth(int birth) {
        this.birth = birth;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_PHONE)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_PHOTOS)
    public Set<String> getPhotos() {
        return photos;
    }

    public void setPhotos(Set<String> photos) {
        this.photos = photos;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_BALLOON)
    public int getBalloon() {
        return balloon;
    }

    public void setBalloon(int balloon) {
        this.balloon = balloon;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_ENDPOINT_ARN)
    public String getEndpointARN() {
        return endpointARN;
    }

    public void setEndpointARN(String endpointARN) {
        this.endpointARN = endpointARN;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_NEW_LIKE_COUNT)
    public int getNewLikeCount() {
        return newLikeCount;
    }

    public void setNewLikeCount(int newLikeCount) {
        this.newLikeCount = newLikeCount;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_NEW_SEND_COUNT)
    public int getNewSendCount() {
        return newSendCount;
    }

    public void setNewSendCount(int newSendCount) {
        this.newSendCount = newSendCount;
    }

    @DynamoDBAttribute(attributeName = ATTRIBUTE_NEW_RECEIVE_COUNT)
    public int getNewReceiveCount() {
        return newReceiveCount;
    }

    public void setNewReceiveCount(int newReceiveCount) {
        this.newReceiveCount = newReceiveCount;
    }
}
